<?php

/**
 * @file
 * CTT Workflow Editor module file.
 */

/**
 * Implements hook_theme().
 */
function ctt_theme() {
  return [
    'ctt_editor' => [
      'variables' => [
        'process_uri' => NULL,
        'api_settings' => [],
        'editor_context' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_install().
 */
function ctt_install() {
  // Grant permissions to administrator role by default.
  $role = \Drupal\user\Entity\Role::load('administrator');
  if ($role) {
    $role->grantPermission('access ctt editor');
    $role->grantPermission('create ctt workflow');
    $role->grantPermission('edit ctt workflow');
    $role->grantPermission('submit ctt workflow');
    $role->grantPermission('administer ctt');
    $role->save();
  }
}
